<?php


namespace frontend\components;


class BlogWidget extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
     return $this->render('blog');
    }

}