<?php


namespace frontend\components;


use common\models\Comment;

class CommentWidget extends \yii\base\Widget
{
    public $comment;
    public function init()
    {
        $this->comment = Comment::find()->where(['status' => 1])->all();
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this->render('comment',['comment' => $this->comment]);
    }

}