<?php


namespace frontend\components;


use common\models\Student;

class ContactWidget extends \yii\base\Widget
{
    public $model;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
     return $this->render('contact',['model' => $this->model]);
    }

}