<?php


namespace frontend\components;


use yii\base\Widget;

class CountsWidget extends Widget
{
    public $applied; // qabul qilingan arizalar soni
    public $all; // Barcha arizalar soni
    public $prosessing; //Ko'rib chiqilmoqda
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
}
public function run()
{
 return $this->render('counts',['applied' => $this->applied, 'all' => $this->all, 'prosessing' => $this->prosessing]);
}
}