<?php


namespace frontend\components;


use common\models\Gallery;

class PortfoloWidget extends \yii\base\Widget
{
    public $gallery;
public function init()
{
    $this->gallery = Gallery::find()->all();
    parent::init(); // TODO: Change the autogenerated stub
}

public function run()
{
 return $this->render('portfolo',['gallery' => $this->gallery]);
}
}