<?php


namespace frontend\components;

use common\models\Dormitory;

/**@var int $applied*/
class ServicesWidget extends \yii\base\Widget
{
    /**
     * @var mixed
     */
    public $dormitory;
    public $applied;

    public function init()
{
    $this->dormitory = Dormitory::find()->all();
    parent::init(); // TODO: Change the autogenerated stub
}
    public function run()
{
 return $this->render('services',['applied' => $this->applied,'models' => $this->dormitory]);
}
}