<?php


namespace frontend\components;




use yii\base\Widget ;

class SliderWidget extends Widget
{
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
}
public function run()
{
    return $this->render('slider');
}
}