<?php


namespace frontend\components;


class ValuesWidget extends \yii\base\Widget
{
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub
}
public function run()
{
 return $this->render('values');
}
}